logging.config: classpath:log/logback-dev.xml
server:
  port: 8081

spring:
  application:
    name: shopServer

eureka.client.service-url.defaultZone:  http://admin:123456@localhost:7071/eureka/
eureka.client.healthcheck.enabled: true
eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${server.port}
eureka.instance.prefer-ip-address: true